[project]
name = "fastapi-gcp-demo"
version = "0.1.0"
description = "This is a sample FastAPI project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
